stages:
    - build
    - test

build:
    stage: build
    image: rust:latest
    script:
        - cargo build --verbose

test:
    stage: test
    image: rust:latest
    script:
        - cargo test --verbose

linting:
    stage: test
    image: realcundo/docker-rust-aio
    script:
        - cargo clippy
        - cargo fmt -- --check
